enum WebsocketType {
  GAMESTATEUPDATE = "GAMESTATEUPDATE",
  CATEGORYUPDATE = "CATEGORYUPDATE",
  TIMEUPDATE = "TIMEUPDATE",
  PLAYERUPDATE = "PLAYERUPDATE",
  POINTSUPDATE = "POINTSUPDATE",
  ROUNDUPDATE = "ROUNDUPDATE",
  GAMEUPDATE = "GAMEUPDATE",
  LOBBYIDUPDATE = "LOBBYIDUPDATE",
}

export default WebsocketType;
